- name: Configuration de Switch3 (L3 - Routage inter-VLAN + ACL)
  hosts: Switch3
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: no

  tasks:
    
    - name: Supprimer les config
      command: "{{ item }}" 
      loop:  
        - net del interface swp1 ip address
        - net del interface swp2 ip address 
        - net commit
      ignore_errors: yes
     
    - name: Configurer le bridge VLAN-aware
      command: net add bridge bridge ports swp1,swp2
          
    - name: ajouter un bridge au vlans
      command: net add bridge bridge vlan-aware
          
    - name: ajouter vids
      command: net add bridge bridge vids 10,20

    - name: Configurer swp1 trunk vers Switch1 (VLAN 10 + 20)
      command: net add interface swp1 bridge trunk vlans 10,20

    - name: Configurer swp2 trunk vers Switch2 (VLAN 10 + 20)
      command: net add interface swp2 bridge trunk vlans 10,20

    - name: Configurer les SVIs - passerelles inter-VLAN
      command: net add vlan 10 ip address 192.168.10.254/24
          
    - name: Configurer les SVIS
      command: net add vlan 20 ip address 192.168.20.254/24

    - name: Activer le routage L3
      command: net add routing defaults datacenter

    - name: Vérifier les interfaces
      command: net show interface
      register: interface_status

    - name: Afficher les interfaces
      debug:
        msg: "{{ interface_status.stdout_lines }}"

    - name: Vérifier les VLANs
      command: net show bridge vlan
      register: vlan_status

    - name: Afficher les VLANs
      debug:
        msg: "{{ vlan_status.stdout_lines }}"

    - name: Vérifier la table de routage
      command: net show route
      register: route_status

    - name: Afficher les routes
      debug:
        msg: "{{ route_status.stdout_lines }}"
